package org.smb;

public class CommonConstents {
	
		//SMBFinance Total Tables
		public static final String TRANSACTION_DETAILS_TABLE = "TRANSACTION_DETAILS";
		public static final String PAYMENT_DETAILS_TABLE = "PAYMENT_DETAILS";
		public static final String ITEM_DETAILS_TABLE ="ITEM_DETAILS";
		public static final String PAYMENT_HISTORY_TABLE ="PAYMENT_HISTORY";
		public static final String CHEETY_PACKAGE_DETAILS = "SMB_CHEETY_PACKAGE_DETAILS";
		public static final String CHEETY_MEMBER_DETAILS = "SMB_CHEETY_MEMBER_DETAILS";
		public static final String CHEETY_SEQ_IDS = "GET_SEQ_IDS";
		public static final String CHEETY_MEMBER_DETAILS_TABLE ="SMB_CHEETY_MEMBER_DETAILS";
		public static final String ADMIN_MEMBER_REGISTION_TABLE ="smb_user_profile";
		public static final String PRODUCT_SEQ_TABLE ="SMB_SEQUENCE_ID";
		public static final String PRODUCT_DETAILS_TABLE = "SMB_PRODUCT_DETAILS";
		public static final String DAILY_LEDGER_DETAILS_TABLE="SMB_DAILY_LEDGER_DETAILS";
		
		//INSERTING QUERYES
		public static final String TRANSACTION_DETAILS_INSERT_QUERY="INSERT INTO "+TRANSACTION_DETAILS_TABLE+"(CUS_ID,CUS_NAME,ADDRESS,BUY_DATE,DUE_TIME,ITEM_NAME,SHOP_NAME,MODEL_NAME,BUY_PRICE,PROFIT,TOT_PRICE,ADVANCE,BAL_AMT,DUE_AMT,TOT_DUES,PER_DUE_AMT,PENALTY,PHONE,INTREST_AMT,TOT_PROFIT,DOC_AMT,PURCHASE_DATE,REC_STATUS) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		public static final String PAYMENT_DETAILS_INSERT_QUERY ="INSERT INTO "+PAYMENT_DETAILS_TABLE+"(CUS_ID,CUS_NAME,ADDRESS,ITEM_NAME,BUY_DATE,DUE_TIME,BAL_DUE_AMT,TOT_DUES,PER_DUE_AMT,NEXT_DUE_AMT,PENALITY,PHONE,REC_STATUS)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		public static final String ITEM_DETAILS_INSERT_QUERY ="INSERT INTO "+ITEM_DETAILS_TABLE+"(CUS_ID,CUS_NAME,BUY_DATE,ITEM_NAME,SHOP_NAME,MODEL_NAME,BUY_PRICE,SALED_PRICE,PROFIT)VALUES (?, ?, ?, ?, ?, ?, ?, ?,?)";
		public static final String PAYMENT_HISTORY_INSERT_QUERY ="INSERT INTO "+PAYMENT_HISTORY_TABLE+"(CUS_ID,PAID_AMT,DUE_DATE,PAY_DATE,BAL_DUE)VALUES (?, ?, ?, ?, ?)";
		public static final String INSERT_ADMIN_CREATION_QUERY ="INSERT INTO "+ADMIN_MEMBER_REGISTION_TABLE+"(USER_TYPE,CREATE_DATE,USER_NAME,USER_PASSWORD,USER_PASSWORD_DUPLICATE,FIRST_NAME)VALUES (?, sysdate(), ?, ?, ?, ?)";
		public static final String PRODUCT_INSERT_QUERY ="INSERT INTO "+PRODUCT_DETAILS_TABLE+"(PROD_ID,PROD_NAME)VALUES (?, ?)";
		public static final String DAILY_LEDGER_INSERT_QUERY ="INSERT INTO "+DAILY_LEDGER_DETAILS_TABLE+"(CUS_ID,TRANS_DATE,TRANS_TYPE,TRANS_MODE,TRANS_AMOUNT)VALUES (?, ?, ?, ?, ?)";
		
		//SELECT QUERYES
		public static final String SELECT_MAX_DUES="SELECT MAX(TOT_DUES) MAXID FROM "+TRANSACTION_DETAILS_TABLE+"";
		public static final String SELECT_ADMIN_USER_ROLES="SELECT * FROM "+ADMIN_MEMBER_REGISTION_TABLE+" ORDER BY USER_TYPE ";
		public static final String SELECT_USER_NAME_DETAILS_QUERY ="SELECT * FROM "+ADMIN_MEMBER_REGISTION_TABLE+" WHERE USER_TYPE=?";
		public static final String SELECT_TOTAL_SALED_PRICE="SELECT SUM(BUY_PRICE) FROM "+ITEM_DETAILS_TABLE+"";
		public static final String SELECT_TOTAL_BUYED_PRICE="SELECT SUM(SALED_PRICE) FROM "+ITEM_DETAILS_TABLE+"";
		public static final String SELECT_TOTAL_PROFIT_PRICE="SELECT SUM(PROFIT) FROM "+ITEM_DETAILS_TABLE+"";
		public static final String SELECT_PRODUCT_DETAILS_ORDERBY_SHOP="SELECT CUS_ID,CUS_NAME,BUY_DATE,ITEM_NAME,SHOP_NAME,MODEL_NAME,BUY_PRICE,SALED_PRICE,PROFIT FROM "+ITEM_DETAILS_TABLE+" ORDER BY SHOP_NAME";
		public static final String SELECT_LEDGER_DETAILS_ORDERBY_DATE="SELECT CUS_ID,TRANS_DATE,TRANS_TYPE,TRANS_MODE,TRANS_AMOUNT FROM "+DAILY_LEDGER_DETAILS_TABLE+" ORDER BY TRANS_DATE";
		public static final String SELECT_PRODUCT_DETAILS_ORDERBY_ITEM="SELECT CUS_ID,CUS_NAME,BUY_DATE,ITEM_NAME,SHOP_NAME,MODEL_NAME,BUY_PRICE,SALED_PRICE,PROFIT FROM "+ITEM_DETAILS_TABLE+" ORDER BY ITEM_NAME";
		public static final String SELECT_PRODUCT_DETAILS="SELECT CUS_ID,CUS_NAME,BUY_DATE,ITEM_NAME,SHOP_NAME,MODEL_NAME,BUY_PRICE,SALED_PRICE,PROFIT FROM "+ITEM_DETAILS_TABLE+" ORDER BY SHOP_NAME";
		public static final String SELECT_CUS_ID_FROM_HISTORY="SELECT * FROM "+PAYMENT_HISTORY_TABLE+" WHERE CUS_ID=?";
		public static final String SELECT_SMB_USER_QUERY ="SELECT FIRST_NAME,USER_NAME,USER_PASSWORD,USER_TYPE FROM "+ADMIN_MEMBER_REGISTION_TABLE+" WHERE USER_NAME = ?";
		public static final String PAYMENT_DETAILS_SELECT_QUERY ="SELECT * FROM "+PAYMENT_DETAILS_TABLE+" WHERE CUS_ID = ?";
		public static final String TRANSACTION_DETAILS_SELECT_QUERY ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+" WHERE CUS_ID = ?";
		//public static final String GET_TRANSACTION_DETAILS_BETWEENDATE ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+" WHERE PURCHASE_DATE BETWEEN STR_TO_DATE(?,'%d-%d-%Y') AND STR_TO_DATE(?,'%d-%d-%Y')";
		public static final String GET_TRANSACTION_DETAILS_BETWEENDATE ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+" WHERE PURCHASE_DATE BETWEEN STR_TO_DATE(?,'%d-%m-%Y') AND STR_TO_DATE(?,'%d-%m-%Y')";
		public static final String GET_DAILY_LEDGER_DETAILS_BETWEENDATE ="SELECT * FROM "+DAILY_LEDGER_DETAILS_TABLE+" WHERE TRANS_DATE BETWEEN STR_TO_DATE(?,'%d-%m-%Y') AND STR_TO_DATE(?,'%d-%m-%Y')";
		public static final String GET_MONTHLY_DUE_DETAILS_BETWEENDATE ="SELECT A.CUS_ID,B.CUS_NAME,A.PAID_AMT,A.PAY_DATE FROM "+PAYMENT_HISTORY_TABLE+" A ,"+TRANSACTION_DETAILS_TABLE+" B WHERE PAY_DATE BETWEEN STR_TO_DATE(?,'%d-%m-%Y') AND STR_TO_DATE(?,'%d-%m-%Y') AND A.CUS_ID = B.CUS_ID  ORDER BY A.PAY_DATE";
		
		//UPDATION QUERYES
		public static final String TRANSACTION_REC_STATUS_UPDATE ="UPDATE "+TRANSACTION_DETAILS_TABLE+" SET REC_STATUS=? WHERE CUS_ID=?";
		public static final String PAYMENT_DETAILS_UPDATE_QUERY = "UPDATE  "+PAYMENT_DETAILS_TABLE+" SET CUS_NAME=?,TOT_DUES=?,PENALITY=?,NEXT_DUE_AMT=?,BAL_DUE_AMT=?,PHONE=?,REC_STATUS=? WHERE CUS_ID= ?";
		public static final String PAYMENT_DETAILS_NON_PENALTY_UPDATE_QUERY = "UPDATE  "+PAYMENT_DETAILS_TABLE+" SET CUS_NAME=?,TOT_DUES=?,NEXT_DUE_AMT=?,BAL_DUE_AMT=?,PHONE=?,REC_STATUS=? WHERE CUS_ID= ?";
		public static final String PRODUCT_SEQ_UPDATE_QUERY = "UPDATE  "+PRODUCT_SEQ_TABLE+" SET SEQ_ID=? WHERE SEQ_NAME = ?";
		
		//DOWNLOAD QUERIES
		public static final String PAYMENT_DETAILS_DOWNLOAD_QUERY_CUSID = "SELECT CUS_ID,CUS_NAME,ADDRESS,ITEM_NAME,BUY_DATE,DUE_TIME,DUE_AMT,TOT_DUES,PER_DUE_AMT,PENALITY,NEXT_DUE_AMT,PHONE FROM "+PAYMENT_DETAILS_TABLE+" ORDER BY CUS_ID DESC";
		public static final String PAYMENT_DETAILS_DOWNLOAD_QUERY_ADDRESS = "SELECT CUS_ID,CUS_NAME,ADDRESS,ITEM_NAME,BUY_DATE,DUE_TIME,DUE_AMT,TOT_DUES,PER_DUE_AMT,PENALITY,NEXT_DUE_AMT,PHONE FROM "+PAYMENT_DETAILS_TABLE+" ORDER BY ADDRESS";
		
		//DOWNLOAD PROFIT DETAILS
		public static final String TOTAL_PAYMENT_DUE_HISTORY_DETAILS ="SELECT * FROM "+PAYMENT_DETAILS_TABLE+" A ,"+PAYMENT_HISTORY_TABLE+" B WHERE A.CUS_ID = B.CUS_ID ORDER BY A.CUS_ID ASC";
		//public static final String PAYMENT_DETAILS_PROFIT_DOWNLOAD_QUERY_ADDRESS = "SELECT * FROM "+TRANSACTION_DETAILS_TABLE+" WHERE PURCHASE_DATE BETWEEN STR_TO_DATE(?,'%D-%M-%Y') AND STR_TO_DATE(?,'%D-%M-%Y')";
		public static final String PAYMENT_DETAILS_PROFIT_DOWNLOAD_QUERY_ADDRESS = "SELECT * FROM "+TRANSACTION_DETAILS_TABLE+" WHERE PURCHASE_DATE BETWEEN STR_TO_DATE(?,'%d-%m-%Y') AND STR_TO_DATE(?,'%d-%m-%Y')";
		
		//SHOW DETAILS QUERIES
		public static final String PAYMENT_HISTORY_TABLE_QUERY ="SELECT * FROM "+PAYMENT_HISTORY_TABLE+" WHERE CUS_ID=?";
		public static final String PAYMENT_DETAILS_TABLE_QUERY ="SELECT * FROM "+PAYMENT_DETAILS_TABLE+" ORDER BY CUS_ID DESC";
		public static final String TRANSACTION_DETAILS_TABLE_QUERY ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+"  ORDER BY CUS_ID DESC";
		public static final String TRANSACTION_DETAILS_TABLE_QUERY_NAME ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+"  ORDER BY CUS_NAME ASC";
		public static final String TRANSACTION_DETAILS_TABLE_QUERY_CUS_ID ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+"  ORDER BY CUS_ID ASC";
		public static final String TRANSACTION_DETAILS_TABLE_QUERY_ADDRESS ="SELECT * FROM "+TRANSACTION_DETAILS_TABLE+"  ORDER BY ADDRESS ASC";
		
		//MAXIMUM AMOUNT QUERIES
		public static final String PAYMENT_DETAILS_SUM_DUE_AMT_QUERY ="SELECT SUM(BAL_DUE_AMT) FROM "+PAYMENT_DETAILS_TABLE+"";
		public static final String PAYMENT_DETAILS_SUM_PER_DUE_AMT_QUERY ="SELECT SUM(PER_DUE_AMT) FROM "+PAYMENT_DETAILS_TABLE+"";
		public static final String PAYMENT_DETAILS_SUM_NEXT_DUE_AMT_QUERY ="SELECT SUM(NEXT_DUE_AMT) FROM "+PAYMENT_DETAILS_TABLE+"";
		
		//DELETE QUERIES
		public static final String ADMIN_USER_DELETE_QUERY ="DELETE FROM "+ADMIN_MEMBER_REGISTION_TABLE+" WHERE USER_TYPE=? AND USER_NAME=?";
		public static final String PAYMENT_DETAILS_DELETE_QUERY ="DELETE FROM "+PAYMENT_DETAILS_TABLE+" WHERE CUS_ID=?";
		public static final String ITEM_DETAILS_DELETE_QUERY ="DELETE FROM "+ITEM_DETAILS_TABLE+" WHERE CUS_ID=?";
		public static final String MULTIPLE_TABLE_DELETE_QUERY ="DELETE "+TRANSACTION_DETAILS_TABLE+", "+PAYMENT_DETAILS_TABLE+" FROM   "+TRANSACTION_DETAILS_TABLE+" JOIN   "+PAYMENT_DETAILS_TABLE+" ON ("+PAYMENT_DETAILS_TABLE+".CUS_ID = "+TRANSACTION_DETAILS_TABLE+".CUS_ID) WHERE  "+TRANSACTION_DETAILS_TABLE+".CUS_ID = ?";
		
		//SELECT PRODUCT QUERIES
		public static final String SELECT_PRODUCT_SEQ_ID ="SELECT SEQ_ID FROM "+PRODUCT_SEQ_TABLE+" WHERE SEQ_NAME = ?";
		
		//SELECT CHEETY QUERIES
		public static final String SELECT_CHEETY_IDS_QUERY ="SELECT * FROM "+CHEETY_PACKAGE_DETAILS+"";
		public static final String SELECT_CHEETY_SEQ_IDS_QUERY ="SELECT * FROM "+CHEETY_SEQ_IDS+"";
		public static final String UPDATE_CHEETY_SEQ_MEM_IDS_QUERY ="UPDATE "+CHEETY_SEQ_IDS+" SET MEMBER_ID = ? WHERE MEMBER_ID = ?"; 
		public static final String UPDATE_CHEETY_SEQ_CHEETY_IDS_QUERY ="UPDATE "+CHEETY_SEQ_IDS+" SET CHEETY_ID = ? WHERE CHEETY_ID = ?"; 
		public static final String INSERT_CHEETY_PACKAGES_QUERY ="INSERT INTO "+CHEETY_PACKAGE_DETAILS+" (CHEETY_ID,CHEETY_NAME,CHEETY_AMOUNT,OWNER_NAME,CHEETY_DATE,TOT_MEMBERS,TOT_MONTHS,PATA_NUMBER) VALUES(? ,? ,? ,? ,? ,? ,? ,?)";
		public static final String INSERT_CHEETY_MEMBERS_QUERY ="INSERT INTO "+CHEETY_MEMBER_DETAILS+" (CHEETY_ID,MEMBER_ID,MEMBER_NAME,ADDRESS,PHONE,CREATE_DATE,PATA_NUMBER,STATUS) VALUES(? ,? ,? ,? ,? ,? ,? ,?)";
		public static final String SELECT_PATA_NUMER_QUERY ="SELECT PATA_NUMBER FROM "+CHEETY_PACKAGE_DETAILS+" WHERE CHEETY_ID = ?";
		public static final String SELECT_CHEETY_UPDATE_DETAILS_QUERY ="SELECT * FROM "+CHEETY_MEMBER_DETAILS_TABLE+" WHERE CHEETY_ID=?";
		public static final String SELECT_CHEETY_PACKAGE_AMOUNT_QUERY ="SELECT * FROM "+CHEETY_PACKAGE_DETAILS+" WHERE CHEETY_ID=?";
		public static final String SELECT_CHEETY_MEMBERS_AMOUNT_QUERY ="SELECT * FROM "+CHEETY_MEMBER_DETAILS_TABLE+"  WHERE CHEETY_ID=? ORDER BY PATA_DATE DESC";
		public static final String UPDATE_CHEETY_MEMBERS_DETAILS_QUERY ="UPDATE "+CHEETY_MEMBER_DETAILS_TABLE+" SET STATUS=?,DUE_AMOUNT=?,PATA_DATE=?,TOT_DUE=?,TOPU_AMOUNT=?,PATA_AMOUNT=?,PATA_NUMBER=?,TAKE_OF_AMOUNT=? WHERE CHEETY_ID=? AND MEMBER_ID=?";
		public static final String UPDATE_PATA_NUMBER_QUERY ="UPDATE "+CHEETY_PACKAGE_DETAILS+" SET PATA_NUMBER=? WHERE CHEETY_ID=?";
	
}
